drop extension if exists "pg_net";

drop policy "Authenticated can insert api key requests" on "public"."api_key_requests";

drop policy "Authenticated can read own api key requests" on "public"."api_key_requests";

revoke delete on table "public"."api_key_requests" from "anon";

revoke insert on table "public"."api_key_requests" from "anon";

revoke references on table "public"."api_key_requests" from "anon";

revoke select on table "public"."api_key_requests" from "anon";

revoke trigger on table "public"."api_key_requests" from "anon";

revoke truncate on table "public"."api_key_requests" from "anon";

revoke update on table "public"."api_key_requests" from "anon";

revoke delete on table "public"."api_key_requests" from "authenticated";

revoke insert on table "public"."api_key_requests" from "authenticated";

revoke references on table "public"."api_key_requests" from "authenticated";

revoke select on table "public"."api_key_requests" from "authenticated";

revoke trigger on table "public"."api_key_requests" from "authenticated";

revoke truncate on table "public"."api_key_requests" from "authenticated";

revoke update on table "public"."api_key_requests" from "authenticated";

revoke delete on table "public"."api_key_requests" from "service_role";

revoke insert on table "public"."api_key_requests" from "service_role";

revoke references on table "public"."api_key_requests" from "service_role";

revoke select on table "public"."api_key_requests" from "service_role";

revoke trigger on table "public"."api_key_requests" from "service_role";

revoke truncate on table "public"."api_key_requests" from "service_role";

revoke update on table "public"."api_key_requests" from "service_role";

alter table "public"."api_key_requests" drop constraint "api_key_requests_user_id_fkey";

alter table "public"."api_key_requests" drop constraint "api_key_requests_pkey";

drop index if exists "public"."api_key_requests_pkey";

drop index if exists "public"."idx_api_key_requests_created_at";

drop index if exists "public"."idx_api_key_requests_status";

drop table "public"."api_key_requests";


  create table "public"."conditions" (
    "condition_id" smallint generated by default as identity not null,
    "name" text not null
      );



  create table "public"."printings" (
    "printing_id" smallint generated by default as identity not null,
    "name" text not null
      );



  create table "public"."product_lines" (
    "product_line_id" integer not null,
    "product_line_name" text not null,
    "product_line_url_name" text,
    "is_direct" boolean
      );



  create table "public"."rarities" (
    "rarity_id" smallint generated by default as identity not null,
    "name" text not null
      );


CREATE UNIQUE INDEX conditions_name_key ON public.conditions USING btree (name);

CREATE UNIQUE INDEX conditions_pkey ON public.conditions USING btree (condition_id);

CREATE INDEX idx_product_lines_name ON public.product_lines USING btree (product_line_name);

CREATE UNIQUE INDEX printings_name_key ON public.printings USING btree (name);

CREATE UNIQUE INDEX printings_pkey ON public.printings USING btree (printing_id);

CREATE UNIQUE INDEX product_lines_pkey ON public.product_lines USING btree (product_line_id);

CREATE UNIQUE INDEX rarities_name_key ON public.rarities USING btree (name);

CREATE UNIQUE INDEX rarities_pkey ON public.rarities USING btree (rarity_id);

alter table "public"."conditions" add constraint "conditions_pkey" PRIMARY KEY using index "conditions_pkey";

alter table "public"."printings" add constraint "printings_pkey" PRIMARY KEY using index "printings_pkey";

alter table "public"."product_lines" add constraint "product_lines_pkey" PRIMARY KEY using index "product_lines_pkey";

alter table "public"."rarities" add constraint "rarities_pkey" PRIMARY KEY using index "rarities_pkey";

alter table "public"."conditions" add constraint "conditions_name_key" UNIQUE using index "conditions_name_key";

alter table "public"."printings" add constraint "printings_name_key" UNIQUE using index "printings_name_key";

alter table "public"."rarities" add constraint "rarities_name_key" UNIQUE using index "rarities_name_key";

grant delete on table "public"."conditions" to "anon";

grant insert on table "public"."conditions" to "anon";

grant references on table "public"."conditions" to "anon";

grant select on table "public"."conditions" to "anon";

grant trigger on table "public"."conditions" to "anon";

grant truncate on table "public"."conditions" to "anon";

grant update on table "public"."conditions" to "anon";

grant delete on table "public"."conditions" to "authenticated";

grant insert on table "public"."conditions" to "authenticated";

grant references on table "public"."conditions" to "authenticated";

grant select on table "public"."conditions" to "authenticated";

grant trigger on table "public"."conditions" to "authenticated";

grant truncate on table "public"."conditions" to "authenticated";

grant update on table "public"."conditions" to "authenticated";

grant delete on table "public"."conditions" to "service_role";

grant insert on table "public"."conditions" to "service_role";

grant references on table "public"."conditions" to "service_role";

grant select on table "public"."conditions" to "service_role";

grant trigger on table "public"."conditions" to "service_role";

grant truncate on table "public"."conditions" to "service_role";

grant update on table "public"."conditions" to "service_role";

grant delete on table "public"."printings" to "anon";

grant insert on table "public"."printings" to "anon";

grant references on table "public"."printings" to "anon";

grant select on table "public"."printings" to "anon";

grant trigger on table "public"."printings" to "anon";

grant truncate on table "public"."printings" to "anon";

grant update on table "public"."printings" to "anon";

grant delete on table "public"."printings" to "authenticated";

grant insert on table "public"."printings" to "authenticated";

grant references on table "public"."printings" to "authenticated";

grant select on table "public"."printings" to "authenticated";

grant trigger on table "public"."printings" to "authenticated";

grant truncate on table "public"."printings" to "authenticated";

grant update on table "public"."printings" to "authenticated";

grant delete on table "public"."printings" to "service_role";

grant insert on table "public"."printings" to "service_role";

grant references on table "public"."printings" to "service_role";

grant select on table "public"."printings" to "service_role";

grant trigger on table "public"."printings" to "service_role";

grant truncate on table "public"."printings" to "service_role";

grant update on table "public"."printings" to "service_role";

grant delete on table "public"."product_lines" to "anon";

grant insert on table "public"."product_lines" to "anon";

grant references on table "public"."product_lines" to "anon";

grant select on table "public"."product_lines" to "anon";

grant trigger on table "public"."product_lines" to "anon";

grant truncate on table "public"."product_lines" to "anon";

grant update on table "public"."product_lines" to "anon";

grant delete on table "public"."product_lines" to "authenticated";

grant insert on table "public"."product_lines" to "authenticated";

grant references on table "public"."product_lines" to "authenticated";

grant select on table "public"."product_lines" to "authenticated";

grant trigger on table "public"."product_lines" to "authenticated";

grant truncate on table "public"."product_lines" to "authenticated";

grant update on table "public"."product_lines" to "authenticated";

grant delete on table "public"."product_lines" to "service_role";

grant insert on table "public"."product_lines" to "service_role";

grant references on table "public"."product_lines" to "service_role";

grant select on table "public"."product_lines" to "service_role";

grant trigger on table "public"."product_lines" to "service_role";

grant truncate on table "public"."product_lines" to "service_role";

grant update on table "public"."product_lines" to "service_role";

grant delete on table "public"."rarities" to "anon";

grant insert on table "public"."rarities" to "anon";

grant references on table "public"."rarities" to "anon";

grant select on table "public"."rarities" to "anon";

grant trigger on table "public"."rarities" to "anon";

grant truncate on table "public"."rarities" to "anon";

grant update on table "public"."rarities" to "anon";

grant delete on table "public"."rarities" to "authenticated";

grant insert on table "public"."rarities" to "authenticated";

grant references on table "public"."rarities" to "authenticated";

grant select on table "public"."rarities" to "authenticated";

grant trigger on table "public"."rarities" to "authenticated";

grant truncate on table "public"."rarities" to "authenticated";

grant update on table "public"."rarities" to "authenticated";

grant delete on table "public"."rarities" to "service_role";

grant insert on table "public"."rarities" to "service_role";

grant references on table "public"."rarities" to "service_role";

grant select on table "public"."rarities" to "service_role";

grant trigger on table "public"."rarities" to "service_role";

grant truncate on table "public"."rarities" to "service_role";

grant update on table "public"."rarities" to "service_role";


